armyimp/apps/w40k/urls.py
from django.urls import include, path
from django.views import generic as generic_views
from rest_framework import routers

from . import views, viewsets

app_name = 'w40k'

router = routers.DefaultRouter()
router.register(r'units', viewsets.UnitViewSet)

urlpatterns = [
    path(r'', generic_views.TemplateView.as_view(template_name='w40k/landing_page.html'),
         name='landing_page'),
    path(r'api/', include(router.urls)),
    path(r'army_unit/', views.ArmyUnitListView.as_view(), name='army_unit_list'),
    path(r'army_unit/create/', views.ArmyUnitCreateView.as_view(), name='army_unit_create'),
    path(r'army_unit/<int:pk>/', views.ArmyUnitDetailView.as_view(), name='army_unit_detail'),
    path(r'unit/', views.UnitListView.as_view(), name='unit_list'),
    path(r'unit/<int:pk>/', views.UnitDetailView.as_view(), name='unit_detail'),
]

armyimp/config/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from armyimp.apps.w40k import urls as w40k_urls

urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^nested_admin/', include('nested_admin.urls')),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'w40k/', include(w40k_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

armyimp/apps/w40k/forms.py
from django import forms
from django.forms import widgets

from . import models


class ArmyModelForm(forms.ModelForm):
    """Form primarily used to add custom validation."""

    def __init__(self, unit, *args, **kwargs):
        """
        Instantiate a new instance.

        Note:
            We require a ``Unit`` instance as an additional argument in order
            to limit the ``model`` queryset to only those ``UnitModel`` instances
            that are viable options for the given unit.
        """
        super().__init__(*args, **kwargs)
        self.fields['model'].queryset = unit.models.all()

    class Meta:
        model = models.ArmyModel
        fields = ('model',)


class ArmyUnitForm(forms.ModelForm):
    """
    Formclass for ``ArmyUnit`` instances.

    Note:
        We change the widget for the ``unit`` field to a ``HiddenInput`` as this should bit be
        user selectable (at least for not) within the form but is passed as a request parameter,
        so we simply need to store its value here.
    """

    class Meta:
        model = models.ArmyUnit
        fields = ('army', 'unit', 'name')
        widgets = {'unit': widgets.HiddenInput}

armyimp/apps/w40k/views.py
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views import generic as generic_views

from . import forms, models


class ArmyUnitCreateView(generic_views.CreateView):
    """View to create a new ``ArmyUnit`` instance."""

    model = models.ArmyUnit
    form_class = forms.ArmyUnitForm
    army_models_formset_prefix = 'models'

    def add_unit(self, data):
        """Add the related unit to the view."""
        unit_pk = data.get('unit')
        self.unit = get_object_or_404(models.Unit, pk=unit_pk)
        return self.unit

    def get(self, request, *args, **kwargs):
        """Use the GET context to fetch the unit."""
        self.add_unit(request.GET)
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        """Use the POST context to fetch the unit."""
        self.add_unit(request.POST)
        return super().post(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        """
        Extend default context.

        In particular:
            - Add ``self.unit``
            - If no army model formset is being passed to the method (due to a
            previous (failed) post request, add a new one.
        """
        context = super().get_context_data(**kwargs)
        context['unit'] = self.unit
        if not context.get('army_model_formset', None):
            context['army_model_formset'] = self.get_army_model_formset()
        return context

    def get_form_kwargs(self):
        """
        Extend default ``kwargs``.

        Include ``Unit`` instance so it can be passed to ``form_class`` as initial data.
        """
        kwargs = super().get_form_kwargs()
        kwargs['initial'] = {'unit': self.unit}
        return kwargs

    def form_valid(self, form):
        """
        Custom handling of validated forms.

        As this function gets called once we successfully validated our main form, we now
        validate the dependent formsets. Only if those validate as well we actually commit
        the new instances to the database and redirect.

        Returns:
            HttpResponseRedirect or self.form_invalid: Redirect to ``self.success_url``
                if all 'child formsets' validated too. Otherwise call ``self.form_invalid``.
        """
        # We can not commit to the db already as we not yet know if the formsets
        # will be valid at all.
        army_unit = form.save(commit=False)
        army_model_formset = self.get_army_model_formset(army_unit)

        if army_model_formset.is_valid():
            self.object = form.save()
            army_model_formset.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.form_invalid(form)

    def get_army_model_formset_class(self):
        """
        Return a customized formset class in order to provide additional validation.

        Note:
            - This formset starts out with exactly the amount of forms
            needed to create this unit's minimal amount of models.
            - It validates that the total mount of forms is at least the model's
            ``models_min`` and does not exceed it's ``models_max``.
        """
        formset_class = inlineformset_factory(
            models.ArmyUnit, models.ArmyModel,
            form=forms.ArmyModelForm, fields=('model',),
            extra=self.unit.models_min, can_delete=False,
            min_num=self.unit.models_min, validate_min=True,
            max_num=self.unit.models_max, validate_max=True
        )
        return formset_class

    def get_army_model_formset(self, instance=None):
        """Construct a formset representing models for this unit."""
        def get_form_kwargs(unit):
            kwargs = {'unit': unit}
            return kwargs

        # Create a dummy instance for the forms 'parent' instance.
        # Needed for the initial GET request.
        if not instance:
            instance = models.ArmyUnit()

        FormsetClass = self.get_army_model_formset_class()  # NOQA

        if self.request.method in ('POST', 'PUT'):
            armymodel_formset = FormsetClass(
                self.request.POST,
                prefix=self.army_models_formset_prefix,
                form_kwargs=get_form_kwargs(self.unit),
                queryset=models.ArmyModel.objects.none(), instance=instance
            )
        else:
            armymodel_formset = FormsetClass(
                prefix=self.army_models_formset_prefix,
                form_kwargs=get_form_kwargs(self.unit),
                queryset=models.ArmyModel.objects.none(), instance=instance
            )
        return armymodel_formset


class ArmyUnitDetailView(generic_views.DetailView):
    """Detail view for ``ArmyUnit`` instances."""

    model = models.ArmyUnit
    context_object_name = 'unit'


class ArmyUnitListView(generic_views.ListView):
    """List view for ``ArmyUnit`` instances."""

    model = models.ArmyUnit


class UnitDetailView(generic_views.DetailView):
    """Detail view for ``ArmyUnit`` instances."""

    model = models.Unit
    context_object_name = 'unit'


class UnitListView(generic_views.ListView):
    """List view for ``Unit`` instances."""

    model = models.Unit

armyimp/apps/w40k/templates/w40k/armyunit_detail.html
{% extends 'w40k/base.html' %}

{% block content %}
<ul>
	<li>Name: {{ unit.name }}</li>
	<li>Army: {{ unit.army }}</li>
	<li>Unit: {{ unit.unit }}</li>
</ul>

<h2>Models</h2>
<ul>
{% for model in unit.models.all %}
	<li>{{ model }}</li>
{% endfor %}
</ul>


{% endblock content %}

armyimp/apps/w40k/templates/w40k/armyunit_form.html
{% extends 'w40k/base.html' %}

{% block content %}
<h1>Create a new army unit</h1>


<form action="" method="post">
	{% csrf_token %}
	{{ form.unit }}
	<p>{{ form.non_field_errors}}</p>
	<p>
		<label for="{{ form.army.id_for_label }}">Army:</label>
		{{ form.army }}
		{{ form.army.errors }}
	</p>
	<p>
		<label for="{{ form.name.id_for_label }}">Name:</label>
		{{ form.name }}
		{{ form.name.errors }}
	</p>

<hr>

{% if unit %}
	<h2>Models</h2>

	{{ army_model_formset.management_form }}
	<p>{{ army_model_formset.non_form_errors }}</p>
	<div id="models">
	{% for form in  army_model_formset %}
		<p>
			<p>{{ form.non_field_errors }}</p>
			<label for="{{ form.model.id_for_label }}">Model:</label>
			{{ form.model }}
			{{ form.model.errors }}
		</p>
	{% endfor %}
	</div>
{% endif %}

	<input type="submit">
</form>
{% endblock content %}

armyimp/apps/w40k/templates/w40k/armyunit_list.html
{% extends 'w40k/base.html' %}

{% block content %}
<h1>All army units</h1>
<ul>
	{% for unit in armyunit_list %}
	<li><a href="{{ unit.get_absolute_url }}">{{ unit }}</a></li>
	{% endfor %}
</ul>
{% endblock content %}

armyimp/apps/w40k/templates/w40k/base.html
{% extends 'base.html' %}

{% block main %}

{% block app_menue %}
<ul>
  <li><a href="{% url 'w40k:landing_page' %}">Landing Page</a></li>
</ul>
{% endblock app_menue %}

{% block content %}
{% endblock content %}

{% endblock main %}

armyimp/apps/w40k/templates/w40k/landing_page.html
{% extends 'w40k/base.html' %}

{% block content %}
<h1>Warhammer 40K</h1>
<h2>Army Management</h2>
<ul>
	<li><a href="{% url 'w40k:army_unit_list' %}">List all army units.</a></li>
</ul>

<h2>Data Management</h2>
<ul>
	<li><a href="{% url 'w40k:unit_list' %}">List all units.</a></li>
</ul>
{% endblock content %}

armyimp/apps/w40k/templates/w40k/unit_detail.html
{% extends 'w40k/base.html' %}

{% block content %}
<ul>
	<li>Name: {{ unit.name }}</li>
	<li>Organization: {{ unit.organization }}</li>
	<li>Category: {{ unit.category }}</li>
	<li>Is named character: {{ unit.is_named_character }}</li>
	<li>Power rating: {{ unit.power_rating }}</li>
	<li>Model price: {{ unit.model_price }}</li>
	<li>Max per army: {{ unit.max_per_army }}</li>
	<li>Minimum amount of models: {{ unit.models_min }}</li>
	<li>Maximum amount of models: {{ unit.models_max }}</li>
	{% if unit.transport %}
		<li>Transport: {{ unit.transport }}</li>
	{% endif %}
	{% if unit.abilities %}
	<li>Abilities:
		<ul>
		{% for each in unit.abilities.all %}
			<li>{{ each }}</li>
			{% endfor %}
		</ul>
	{% endif %}
</ul>
{% endblock content %}

armyimp/apps/w40k/templates/w40k/unit_list.html
{% extends 'w40k/base.html' %}

{% block content %}
<h1>All units</h1>
<ul>
	{% for unit in unit_list %}
	<li>
		<a href="{{ unit.get_absolute_url }}">{{ unit }}</a>
		<a href="{% url 'w40k:army_unit_create' %}?unit={{ unit.pk }}">[Add to existing army]</a>
	</li>
	{% endfor %}
</ul>
{% endblock content %}